version: '3.8'

services:
  wog_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amitkemp10/wog_app:v1.0
    container_name: wog_app_container
    command: python main_score.py
    volumes:
      - .:/wog_app
      - ./Scores.txt:/wog_app/Scores.txt
    ports:
      - "8777:5000"
